#!/bin/sh
# Generate a supervisord config from $BRIDGES, then run it.
#
# `bbctl run` handles exactly ONE bridge per process, so running several
# bridges in one container needs a supervisor with one program per bridge.
# The list is a runtime input rather than baked into the image, so the image
# stays generic (and carries no information about whose bridges these are).
#
# BRIDGES is a comma/space separated list of "name" or "name:type":
#   BRIDGES="whatsapp,signal,meta:meta,instagram:instagram"
# Each entry becomes a program running the base image's own run-bridge.sh with
#   BRIDGE_NAME=${BRIDGE_PREFIX}<name>   (default prefix "sh-", required by bbctl)
#   BEEPER_BRIDGE_TYPE=<type>            (only when given)
#   BBCTL_CONFIG=${DATA_DIR}/bbctl/<name>.json
#
# Why <type> is worth setting explicitly: bbctl otherwise guesses it with a
# strings.Contains over an ordered table, so the guess depends on substring
# order. Passing it removes the ambiguity.
#
# Why BBCTL_CONFIG is per bridge: bbctl re-saves that file to backfill the
# username after a whoami, so one shared file would be a write race between
# the running bridges.
#
# Everything else (MATRIX_ACCESS_TOKEN, BEEPER_ENV, DATA_DIR, DB_DIR, and any
# BEEPER_BRIDGE_* flags such as BEEPER_BRIDGE_NO_OVERRIDE_CONFIG) is inherited
# from the container environment by every program, so it is set once on the
# container rather than repeated per bridge.
set -eu

# /etc/supervisord.conf is supervisorctl's default search path, so writing it
# there keeps `supervisorctl status` working with no arguments — which the
# documented healthcheck and every operator reflex rely on.
CONF=${SUPERVISORD_CONF:-/etc/supervisord.conf}
BRIDGE_PREFIX=${BRIDGE_PREFIX:-sh-}
DATA_DIR=${DATA_DIR:-/data}
START_SECS=${BRIDGE_START_SECS:-30}
STOP_WAIT_SECS=${BRIDGE_STOP_WAIT_SECS:-30}

if [ -z "${BRIDGES:-}" ]; then
	echo "BRIDGES is not set — nothing to run." >&2
	echo 'Example: BRIDGES="whatsapp,signal,telegram"' >&2
	exit 1
fi

cat > "$CONF" <<CONFEOF
; GENERATED by docker-entrypoint.sh from \$BRIDGES — edits here are lost on
; restart. Change BRIDGES (or BRIDGE_PREFIX) on the container instead.
[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0
pidfile=/tmp/supervisord.pid

[unix_http_server]
file=/tmp/supervisor.sock

[rpcinterface:supervisor]
supervisor.rpcinterface_factory = supervisor.rpcinterface:make_main_rpcinterface

[supervisorctl]
serverurl=unix:///tmp/supervisor.sock
CONFEOF

count=0
for entry in $(echo "$BRIDGES" | tr ',' ' '); do
	name=${entry%%:*}
	type=${entry#"$name"}
	type=${type#:}

	# bbctl requires 1-32 chars of [a-z0-9-]; the prefix counts toward that.
	case "$name" in
		*[!a-z0-9-]* | "")
			echo "Invalid bridge name '$name' (allowed: a-z, 0-9, -)" >&2; exit 1 ;;
	esac

	{
		echo
		echo "[program:${name}]"
		# mkdir here (not at image build) because \$DATA_DIR is a volume.
		echo "command=/bin/sh -c 'mkdir -p ${DATA_DIR}/bbctl && exec /usr/local/bin/run-bridge.sh'"
		printf 'environment=BRIDGE_NAME="%s%s"' "$BRIDGE_PREFIX" "$name"
		[ -n "$type" ] && printf ',BEEPER_BRIDGE_TYPE="%s"' "$type"
		printf ',BBCTL_CONFIG="%s/bbctl/%s.json"\n' "$DATA_DIR" "$name"
		echo "autostart=true"
		echo "autorestart=true"
		echo "startsecs=${START_SECS}"
		echo "startretries=1000"
		# run-bridge.sh does not exec, so the shell stays the parent of bbctl,
		# which in turn spawns the bridge binary. Without stop/killasgroup a
		# stop would signal only the shell and leak the bridge process.
		echo "stopasgroup=true"
		echo "killasgroup=true"
		echo "stopwaitsecs=${STOP_WAIT_SECS}"
		echo "stdout_logfile=/dev/fd/1"
		echo "stdout_logfile_maxbytes=0"
		echo "redirect_stderr=true"
	} >> "$CONF"
	count=$((count + 1))
done

echo "Configured ${count} bridge(s) from \$BRIDGES" >&2

# Print the generated config and exit — for testing, without starting anything.
if [ -n "${GENERATE_ONLY:-}" ]; then
	cat "$CONF"
	exit 0
fi

exec /usr/bin/supervisord -c "$CONF"
